#!/usr/bin/env bash

set -euo pipefail

uname="$(uname)"
case "$uname" in
    Darwin)
        echo "Not yet implemented, need to steal from halyard/halyard"
        exit 1
        ;;
    Linux)
        # Only really supports Ubuntu 16.04, patches welcome
        wget https://apt.puppetlabs.com/puppet5-release-xenial.deb
        dpkg -i puppet5-release-xenial.deb
        apt update
        rm puppet5-release-xenial.deb
        apt install puppet-agent
        ;;
    *)
        echo "Support for $uname not implemented"
        exit 1
        ;;
esac

mkdir -p /opt/halyard/repo
git clone --recursive git://github.com/halyard/goblin /opt/halyard/repo
/opt/halyard/repo/meta/puppet-run

