#!/usr/bin/env bash

set -euo pipefail

uname="$(uname)"
case "$uname" in
    Darwin)
        echo "Mac support not yet implemented, need to steal from halyard/halyard"
        exit 1
        ;;
    Linux)
        distro="$(grep ID= /etc/os-release | cut -d= -f2)"
        case "$distro" in
            archarm|arch)
                pacman -Syu --noconfirm --needed puppet git
                ;;
            *)
                echo "Support for this Linux distro ($distro) not yet implemented"
                exit 1
                ;;
        esac
        ;;
    *)
        echo "Support for $uname not implemented"
        exit 1
        ;;
esac

mkdir -p /opt/halyard/repo
git clone --recursive git://github.com/halyard/goblin /opt/halyard/repo
/opt/halyard/repo/meta/puppet-run

